#!/bin/sh
#
# chkconfig: 35 98 98
# description: titan
#

. /etc/rc.d/init.d/functions

USER="ec2-user"

ROOT_DIR="/home/ec2-user/Dev/titan"
SERVER="$ROOT_DIR/run.sh"
LOG_FILE="/home/ec2-user/logs/titan.log"
LOCK_FILE="/var/lock/subsys/titan"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting titan: "
                runuser -l "$USER" -c "cd $ROOT_DIR && $SERVER >> $LOG_FILE 2>&1 &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "titan is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep phoenix | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
